### ISSUE TITLE
IIN #2 ⁃ badger vs possum

### ISSUE THREAD

**Issue by securingmom** [privacyone/supporting-extensions#1]
Why have you chosen Privacy Badger instead of Privacy Possum? 

https://github.com/cowlicks/privacypossum

**Comment by dragoljubm** [comment]
Privacy Possum was included in Breeze during earlier development but was dropped mainly due to the fact that tracking companies and technologies are becoming more and more advanced on a daily basis whilst Privacy Possum hadn't been updated in quite a while.

**Comment by alexander-cato** [comment]
Possum is no longer maintained by the original developers and we don't have the resources to maintain it ourselves. Outdated and unmaintained code poses a security threat and we replaced most of Possum's functionality not included in Badger with [ClearURLs](https://gitlab.com/KevinRoebert/ClearUrls)
